const Router=require("express").Router()

const MaincategoryRouter=require("../routes/MaincategoryRoutes")
const SubcategoryRouter=require("../routes/SubcategoryRoutes")
const BrandRouter=require("../routes/BrandRoutes")
const ProductRouter=require("../routes/ProductRoutes")
const FeatureRouter=require("../routes/FeatureRoutes")
const FaqRouter=require("../routes/FaqRoutes")
const SettingRouter=require("../routes/SettingRoutes")
const UserRouter=require("../routes/UserRoutes")
const CartRouter=require("../routes/CartRoutes")
const WishlistRouter=require("../routes/WishlistRoutes")
const CheckoutRouter=require("../routes/CheckoutRoutes")
const NewsletterRouter=require("../routes/NewsletterRoutes")
const ContactusRouter=require("../routes/ContactusRoutes")
const TestimonialRouter=require("../routes/TestimonialRoutes")

Router.use("/maincategory",MaincategoryRouter)
Router.use("/subcategory",SubcategoryRouter)
Router.use("/brand",BrandRouter)
Router.use("/product",ProductRouter)
Router.use("/feature",FeatureRouter)
Router.use("/faq",FaqRouter)
Router.use("/setting",SettingRouter)
Router.use("/user",UserRouter)
Router.use("/cart",CartRouter)
Router.use("/wishlist",WishlistRouter)
Router.use("/checkout",CheckoutRouter)
Router.use("/newsletter",NewsletterRouter)
Router.use("/contactus",ContactusRouter)
Router.use("/testimonial",TestimonialRouter)

module.exports=Router